In [1]:
import numpy as np

[1 2 3 4]


In [2]:
#attributes of numpy
arr=np.array([1,2,3,4])   #value, datatype
print(arr)

print(arr.ndim)  #dimension
print(arr.shape)  #shape
print(arr.dtype)  #data type    
print(arr.size)   #size


[1 2 3 4]
1
(4,)
int64
4


In [7]:
#methods
arr= np.array(((1,2),(3,"ABC")))  #value, datatype # to create array
#print(arr)  #to print array

print(np.arange(3)) # start, stop, step
print(np.random.rand(1,2)) #to create random array
print(np.random.randint(1,10,12)) #  start,end, ele


[0 1 2]
[[0.4601423  0.52223398]]
[3 1 2 3 1 8 4 8 4 7 7 1]


In [10]:
# create a guessing game where user will enter a number you have tell number is big or small
# loop user will enter another number make it untill user guess the number
# add num,subs num
num = np.random.randint(0,10)
user = int(input("enter a number :"))
while(num != user):
    user = int(input("enter a number :"))
    if (num == user):
        print("you won")
    elif(num>user):
        print("guess a large number")
    else:
        print("guess a small number ")



guess a large number
guess a small number 
you won


In [16]:
#zero 
print(np.zeros((3,4,2),dtype=int)) #shape, datatype

[[[0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]]]


In [ ]:
arr=np.random.randint(1,10,12)
print(arr)
print(arr.shape)
print(arr.reshape(3,4)) #reshape
print(arr)


[4 8 6 9 2 2 6 8 4 6 3 4]
(12,)
[[4 8 6 9]
 [2 2 6 8]
 [4 6 3 4]]
[4 8 6 9 2 2 6 8 4 6 3 4]


In [18]:
arr+arr  #add

array([ 8, 16, 12, 18,  4,  4, 12, 16,  8, 12,  6,  8], dtype=int32)

In [19]:
list1 = [1,2,3,4]
list1+list1

[1, 2, 3, 4, 1, 2, 3, 4]

In [24]:
#max ,min,argmax,argmin
print(arr)
max(arr)
arr.max()    #np method
max(list1)  #py function

arr.min()
arr.argmax()  #index of max
arr.argmin()  #index of min
arr.mean()  #mean
arr.std()   #standard deviation


[4 8 6 9 2 2 6 8 4 6 3 4]


np.float64(2.266911751455907)

In [25]:
arr[3] #indexing
arr[0:5] #slicing   

array([4, 8, 6, 9, 2], dtype=int32)

In [26]:
np.flip(arr) #reverse the array

array([4, 3, 6, 4, 8, 6, 2, 2, 9, 6, 8, 4], dtype=int32)

In [29]:
np.arange(1,30,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [ ]:
arr= arr.reshape(3,5)
arr

In [ ]:
print()